-- Synced demo posts for FK on comments/likes/saves (run after schema.sql)
-- Generated by scripts/emit-seed-sql.ts — do not edit by hand

INSERT INTO public.posts (id, title, excerpt, content, date, read_time, tags, cover_emoji, photo_urls)
VALUES (
  'transformer-architecture-deep-dive',
  'Transformer Architecture: A Deep Dive into Attention Mechanisms',
  'Understanding the revolutionary architecture behind GPT, BERT, and modern LLMs. How self-attention changed NLP forever.',
  $post_0_transformer_architecture_deep_dive$The Transformer architecture, introduced in the seminal paper "Attention Is All You Need" by Vaswani et al. in 2017, has fundamentally reshaped the landscape of natural language processing and beyond.

## Why Transformers Matter

Before transformers, recurrent neural networks (RNNs) and LSTMs dominated sequence modeling. However, they suffered from vanishing gradients and couldn't parallelize effectively. The transformer solved both problems with a single elegant idea: self-attention.

## Self-Attention Mechanism

The core innovation is the scaled dot-product attention:

**Attention(Q, K, V) = softmax(QK^T / √d_k) V**

Each token in a sequence can attend to every other token simultaneously. This allows the model to capture long-range dependencies that RNNs struggle with.

## Multi-Head Attention

Rather than computing a single attention function, transformers use multiple attention heads. Each head learns different types of relationships — some focus on syntax, others on semantics, and some on positional patterns.

## Positional Encoding

Since transformers process all tokens simultaneously (unlike sequential RNNs), they need positional information injected explicitly. The original paper used sinusoidal functions, but modern variants like RoPE and ALiBi have improved upon this.

## Impact on the Field

From BERT to GPT-4, from Vision Transformers to AlphaFold, the transformer architecture has become the universal backbone of modern AI. Understanding it deeply is essential for any ML practitioner working today.

The key takeaway: attention mechanisms allow models to dynamically focus on relevant parts of the input, making them incredibly flexible and powerful.$post_0_transformer_architecture_deep_dive$,
  '2025-02-10',
  '1 year ago',
  ARRAY['Transformers', 'NLP', 'Deep Learning']::text[],
  '🧠',
  ARRAY['/vanilla-Transformer-attention-mechanism-with-a-detailed-explanation-diagram.jpg']::text[]
)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  excerpt = EXCLUDED.excerpt,
  content = EXCLUDED.content,
  date = EXCLUDED.date,
  read_time = EXCLUDED.read_time,
  tags = EXCLUDED.tags,
  cover_emoji = EXCLUDED.cover_emoji,
  photo_urls = EXCLUDED.photo_urls;

INSERT INTO public.posts (id, title, excerpt, content, date, read_time, tags, cover_emoji, photo_urls)
VALUES (
  'building-rag-systems-production',
  'Building RAG Systems for Production: Lessons from the Trenches',
  'Practical insights on building Retrieval-Augmented Generation systems that actually work at scale. Chunking strategies, embedding models, and evaluation.',
  $post_1_building_rag_systems_production$After building multiple RAG systems at scale, I've learned that the gap between a demo and production is enormous. Here are the hard-won lessons.

## The RAG Pipeline

A production RAG system has several critical components:
1. **Document Ingestion** — parsing, cleaning, chunking
2. **Embedding Generation** — choosing the right model
3. **Vector Store** — indexing and retrieval
4. **Context Assembly** — ranking and filtering
5. **LLM Generation** — prompt engineering and guardrails

## Chunking Strategies That Work

The most common mistake is naive fixed-size chunking. Instead, consider:
- **Semantic chunking**: Split at natural boundaries (paragraphs, sections)
- **Recursive character splitting**: With overlap for context preservation
- **Document-aware chunking**: Respect headers, tables, and code blocks

## Embedding Model Selection

Not all embedding models are created equal. For production:
- **OpenAI text-embedding-3-large**: Great general-purpose choice
- **Cohere embed-v3**: Excellent multilingual support
- **BGE/GTE models**: Strong open-source alternatives

## Evaluation is Everything

You can't improve what you can't measure. Build evaluation pipelines early:
- **Retrieval quality**: MRR, NDCG, recall@k
- **Generation quality**: Faithfulness, relevance, completeness
- **End-to-end**: Human evaluation with clear rubrics

## Key Production Lessons

1. Metadata filtering beats pure semantic search
2. Hybrid search (BM25 + dense) outperforms either alone
3. Re-ranking is often the biggest quality lever
4. Monitor for drift — your documents and queries change over time$post_1_building_rag_systems_production$,
  '2025-08-28',
  '6+ months read',
  ARRAY['RAG', 'LLM', 'Production ML']::text[],
  '🔍',
  ARRAY['/1753178843164.png']::text[]
)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  excerpt = EXCLUDED.excerpt,
  content = EXCLUDED.content,
  date = EXCLUDED.date,
  read_time = EXCLUDED.read_time,
  tags = EXCLUDED.tags,
  cover_emoji = EXCLUDED.cover_emoji,
  photo_urls = EXCLUDED.photo_urls;

INSERT INTO public.posts (id, title, excerpt, content, date, read_time, tags, cover_emoji, photo_urls)
VALUES (
  'voice-ai-alexa-experience',
  'What I Learned Building Voice AI at Amazon Alexa',
  'Reflections on my time working on Alexa''s NLU pipeline — the challenges of real-time inference, handling ambiguity, and building for millions.',
  $post_2_voice_ai_alexa_experience$Working on Amazon Alexa was one of the most formative experiences of my career. Here's what I learned about building voice AI at massive scale.

## The Scale Challenge

Alexa processes billions of requests daily. Every millisecond of latency matters. Every 0.1% improvement in accuracy impacts millions of users. This fundamentally changes how you think about ML.

## Real-Time NLU Pipeline

The natural language understanding pipeline has to:
1. Process speech-to-text output (often noisy)
2. Identify the user's intent
3. Extract relevant entities (slots)
4. Route to the correct skill
5. All within strict latency budgets

## Handling Ambiguity

"Play something good" — what does this mean? Music? A podcast? A game? Ambiguity is the fundamental challenge of voice AI. We built confidence scoring systems and fallback strategies that gracefully handle uncertainty.

## Model Serving at Scale

Key lessons in serving ML models:
- **Model distillation** is essential for latency-critical paths
- **A/B testing** everything, always
- **Canary deployments** saved us countless times
- **Feature stores** for consistent feature computation

## The Human Element

The biggest insight: users don't think in terms of intents and entities. They speak naturally, with context, emotion, and cultural nuances. Building truly natural voice AI requires deep empathy with users.

## What I'd Do Differently

If starting over, I'd invest more in:
- End-to-end models vs. pipeline approaches
- Better evaluation frameworks from day one
- More diverse training data earlier in development$post_2_voice_ai_alexa_experience$,
  '2023-01-15',
  '2 years read',
  ARRAY['Voice AI', 'Alexa', 'NLU']::text[],
  '🎤',
  ARRAY['/alexa.jpg']::text[]
)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  excerpt = EXCLUDED.excerpt,
  content = EXCLUDED.content,
  date = EXCLUDED.date,
  read_time = EXCLUDED.read_time,
  tags = EXCLUDED.tags,
  cover_emoji = EXCLUDED.cover_emoji,
  photo_urls = EXCLUDED.photo_urls;

INSERT INTO public.posts (id, title, excerpt, content, date, read_time, tags, cover_emoji, photo_urls)
VALUES (
  'fine-tuning-llms-practical-guide',
  'A Practical Guide to Fine-Tuning LLMs in 2026',
  'When to fine-tune, when to prompt engineer, and how to do it right. Covering LoRA, QLoRA, and full fine-tuning approaches.',
  $post_3_fine_tuning_llms_practical_guide$Fine-tuning LLMs has become more accessible than ever, but knowing when and how to do it effectively is still an art.

## When to Fine-Tune vs. Prompt Engineer

**Use prompt engineering when:**
- Your task can be described with examples
- You need flexibility to change behavior quickly
- You have limited training data

**Fine-tune when:**
- You need consistent output format
- Domain-specific knowledge is critical
- Latency requirements are strict (smaller fine-tuned models)
- You have quality training data (1000+ examples)

## LoRA: The Default Choice

Low-Rank Adaptation has become the standard for efficient fine-tuning:
- Train only ~0.1% of parameters
- Mergeable into base model for zero-overhead inference
- Works with quantized models (QLoRA) for even lower memory

## Data Quality > Data Quantity

The single most important factor is training data quality. I've seen 500 carefully curated examples outperform 50,000 noisy ones. Invest in:
- Clear, consistent labeling guidelines
- Human review of training examples
- Diversity in examples (edge cases matter)

## Evaluation Framework

Before fine-tuning, define your evaluation:
1. **Automated metrics**: BLEU, ROUGE for text generation; accuracy for classification
2. **LLM-as-judge**: Use a stronger model to evaluate outputs
3. **Human evaluation**: Essential for nuanced quality assessment

## Common Pitfalls

- **Catastrophic forgetting**: Use low learning rates and short training
- **Overfitting**: Always hold out a validation set
- **Distribution shift**: Ensure training data matches production inputs
- **Ignoring base model updates**: Re-evaluate when new base models release$post_3_fine_tuning_llms_practical_guide$,
  '2026-01-02',
  '9 min read',
  ARRAY['Fine-Tuning', 'LLM', 'LoRA']::text[],
  '⚡',
  ARRAY['/medium_data_ccbd9e0d2c.png']::text[]
)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  excerpt = EXCLUDED.excerpt,
  content = EXCLUDED.content,
  date = EXCLUDED.date,
  read_time = EXCLUDED.read_time,
  tags = EXCLUDED.tags,
  cover_emoji = EXCLUDED.cover_emoji,
  photo_urls = EXCLUDED.photo_urls;

INSERT INTO public.posts (id, title, excerpt, content, date, read_time, tags, cover_emoji, photo_urls)
VALUES (
  'ml-system-design-interviews',
  'Cracking ML System Design Interviews: My Framework',
  'A structured approach to ML system design questions, drawn from my experience interviewing at top tech companies and LeetCode rank 234.',
  $post_4_ml_system_design_interviews$Having gone through dozens of ML system design interviews and achieving a LeetCode rank of 234, here's the framework I use and recommend.

## The 4-Step Framework

### Step 1: Clarify Requirements (5 minutes)
- What is the business objective?
- What are the constraints (latency, throughput, cost)?
- What data is available?
- What are the success metrics?

### Step 2: High-Level Design (10 minutes)
- Draw the end-to-end pipeline
- Identify offline vs. online components
- Define data flow and storage
- Outline model architecture choices

### Step 3: Deep Dive (15 minutes)
- Feature engineering details
- Model selection and training strategy
- Serving architecture
- Monitoring and feedback loops

### Step 4: Trade-offs and Extensions (10 minutes)
- Discuss alternatives you considered
- Scale considerations
- Edge cases and failure modes
- Future improvements

## Common ML System Design Questions

1. **Design a recommendation system** — collaborative filtering, content-based, hybrid
2. **Design a search ranking system** — two-stage retrieval + ranking
3. **Design a fraud detection system** — real-time vs. batch, feature engineering
4. **Design an ad click prediction system** — feature stores, real-time serving

## Key Principles

- **Start simple, then iterate**: Don't jump to the most complex solution
- **Think about data first**: The best model can't fix bad data
- **Consider the full lifecycle**: Training, serving, monitoring, retraining
- **Communicate trade-offs**: Show you understand the engineering cost of decisions

## LeetCode Tips

Getting to rank 234 required consistent practice:
- Focus on patterns, not individual problems
- Spend 20 minutes thinking before coding
- Review solutions even when you solve correctly
- Practice explaining your approach out loud$post_4_ml_system_design_interviews$,
  '2025-12-18',
  '11 min read',
  ARRAY['System Design', 'Interviews', 'Career']::text[],
  '🎯',
  ARRAY['/FastViT_2x.png']::text[]
)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  excerpt = EXCLUDED.excerpt,
  content = EXCLUDED.content,
  date = EXCLUDED.date,
  read_time = EXCLUDED.read_time,
  tags = EXCLUDED.tags,
  cover_emoji = EXCLUDED.cover_emoji,
  photo_urls = EXCLUDED.photo_urls;

