/**
 * Generates supabase/seed_blog_posts.sql from src/data/blogPosts.ts
 * Run: npx tsx scripts/emit-seed-sql.ts
 */
import { writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { blogPosts } from '../src/data/blogPosts';

const __dirname = dirname(fileURLToPath(import.meta.url));
const outPath = join(__dirname, '..', 'supabase', 'seed_blog_posts.sql');

function escSqlString(s: string): string {
  return s.replace(/'/g, "''");
}

function dollarTag(id: string, index: number): string {
  const safe = id.replace(/[^a-zA-Z0-9]/g, '_');
  return `post_${index}_${safe}`;
}

let sql = `-- Synced demo posts for FK on comments/likes/saves (run after schema.sql)
-- Generated by scripts/emit-seed-sql.ts — do not edit by hand

`;

for (let i = 0; i < blogPosts.length; i++) {
  const p = blogPosts[i];
  const tag = dollarTag(p.id, i);
  const tagsSql = p.tags.map((t) => `'${escSqlString(t)}'`).join(', ');
  const photosSql = p.photoUrls.map((u) => `'${escSqlString(u)}'`).join(', ');

  sql += `INSERT INTO public.posts (id, title, excerpt, content, date, read_time, tags, cover_emoji, photo_urls)
VALUES (
  '${escSqlString(p.id)}',
  '${escSqlString(p.title)}',
  '${escSqlString(p.excerpt)}',
  $${tag}$${p.content}$${tag}$,
  '${p.date}',
  '${escSqlString(p.readTime)}',
  ARRAY[${tagsSql}]::text[],
  '${escSqlString(p.coverEmoji)}',
  ARRAY[${photosSql}]::text[]
)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  excerpt = EXCLUDED.excerpt,
  content = EXCLUDED.content,
  date = EXCLUDED.date,
  read_time = EXCLUDED.read_time,
  tags = EXCLUDED.tags,
  cover_emoji = EXCLUDED.cover_emoji,
  photo_urls = EXCLUDED.photo_urls;

`;
}

writeFileSync(outPath, sql, 'utf8');
console.log('Wrote', outPath);
